BASE_URL = 'https://github.com/guga31bb/nflfastR-data/blob/master/data/play_by_play_{year}.csv.gz?raw=True'
ROSTER_URL = 'https://raw.githubusercontent.com/nflverse/nflfastR-roster/master/data/seasons/roster_{year}.csv'
DEPTH_CHART_URL = 'https://github.com/nflverse/nflfastR-roster/blob/master/data/seasons/depth_charts_{year}.csv.gz?raw=True'
INJURY_URL = 'https://github.com/nflverse/nflfastR-roster/blob/master/data/seasons/injuries_{year}.csv.gz?raw=True'
TEAM_LOGO_URL = 'https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/teams_colors_logos.csv'
SCHEDULE_URL = 'https://github.com/guga31bb/nflfastR-data/blob/master/schedules/sched_{year}.rds?raw=True'
